# Generated by Django 2.2.3 on 2019-08-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attenders',
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TextField(default='0:00'),
            preserve_default=False,
        ),
    ]
