# Generated by Django 2.2.3 on 2019-08-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='tile',
            new_name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
