# Generated by Django 2.2.3 on 2019-08-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_auto_20190802_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.TextField(),
        ),
    ]
