# Generated by Django 2.2.3 on 2019-08-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_auto_20190802_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attenders',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
