# Generated by Django 2.2.3 on 2019-08-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_event_attenders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attenders',
            field=models.IntegerField(default=0),
        ),
    ]
